# Generated by Django 3.0.3 on 2020-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('AT', 'Atualizações'), ('PR', 'Projetos')], default='------', max_length=2),
        ),
    ]
