# Generated by Django 3.0.3 on 2020-02-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200214_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('AT', 'Atualizações'), ('PR', 'Projetos')], default='None', max_length=2),
        ),
    ]
