# Generated by Django 3.0.3 on 2020-02-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200214_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('AT', 'Atividades'), ('PR', 'Projetos')], default='Atividades', max_length=2),
        ),
    ]
