# Generated by Django 3.0.3 on 2020-02-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
